### ISSUE TITLE
design of Implementation

### ISSUE THREAD

**Issue by Bemhreth** [Bemhreth/intelligent-agent#7]

**Comment by Bemhreth** [comment]
can you send the UML design here?

**Comment by kkalkidan** [comment]
[UML design](https://app.diagrams.net?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#R7Zrbbts4EIafxkB70UIHy3YufdoErbNNE2DbvQoYi5bYUBwtRcV2nn5JibSs0HG9rVxtAQEGZP4aioePwyEl9vxpsrnkKI2vIcS05znhpufPep7n%2Bn1XXpSyLZXhUAsRJ6E2qoQ78oy16Gg1JyHOaoYCgAqS1sUlMIaXoqYhzmFdN1sBrZeaoghbwt0SUVv9QkIRl%2BoocCr9CpMoNiW7jr6TIGOshSxGIaz3JH%2Fe86ccQJT%2Fks0UU9V5pl%2FKfH%2B8cndXMY6ZOCXD7e34n8UH7%2FPVbPl1%2FRnmZLa6eNfXdRNb02AcyvbrJHARQwQM0XmlTjjkLMTqqY5MVTYLgFSKrhS%2FYSG2GibKBUgpFgnVd2WF%2BfarTLxz3jv%2BwCh%2Fa2U4NMpsowspU9v91A3mJMECcy2WDVG1f7V%2FtJRBzpfaKhyMH2%2BGaTC%2Fwlf5x%2Bs%2FyYcoNJ0iEI%2BwOGJXPlD39iUGWR2%2BlRk5pkiQp3pFkB6I0c6uYiX%2FaFyH0R2r5ROiuS7pS56keSa1NXA5zKdeb%2BxYfLM1SShiCuQKmDCoVRcuY0LDBdpCrlqdCbR8NKlJDJw8S3tkIMrbXGjEnmK4IpROgYICwqAooMp0px6mi%2BE4k9luDBj3hXSNNjXDBcqEqSBQitKMPBRVVhkTyYiwCQgBSW0gHOD%2BhLnAmz3JJmfuDnS%2F6UnLNz68rqYAt6%2B1uO7%2BZ6IdWLRvARIFuxdM%2Br1gZi4vecsmiwIXh0f8gs8BZIiSiMkkxSuVTfUZkbPhWMtCufgkS9GSsGhR2Mz6lXKru0JJIPOuaDHjxSQMMSumDoEEetiNuBQIE0VXBRP5k503dd4HRTOmMu1WaflT5lxMgcm2IFLAxXJsrLEaHwewH%2FWa748FzV6O7ZPQG7vGyQ8s8qrtnnOJEtlyJHCHvGHkgdcy8qGFvOdNVHRjMt69GUe4GABIXd929BumPxydRt%2F3zkTf9Q7O9V0k%2F4FI7gdBLZJfnBjIPWd0Lrq%2BRfeGiM6Lj3vxzid%2Bn7jt2gt06Qf4uYvXjbNuPWC79vLcbMY61s2yPjU8n431LghVrO8EZsu4Y900a9fptwy7b6%2FFLikR6rVTR7tp2v6pi7Ozuba9NvuLZETgsKPdOO2g7QWaKWyP9qePHejGQY%2FaXp2NLM76FUq3of7PG%2BpB8OLVuNv6jvrCwtu9Fj3Bk0cno%2F%2Ff7KjtCTsFGZ4JsA52w7Bb31J79nePRwZrqr7w3j%2BgrPPvppG3vrN2X%2FvuIXLO7hWnN93njqapt7%2FHdu312R52rmrQcW%2Bee%2Bu7bddeuJXcE9nF9yvga8TDjnzz5FvfeXv2Qq4kn8UAnbOfAfmv3IMfPGgYWEx%2F5UHDXUKdMVQwjh8wLOvayFlCs6b57mHC4DDAnz1LKJPVEdPi3t5BXX%2F%2BLw%3D%3D)

**Comment by Bemhreth** [comment]
we wiil upgrade it as we go.
